# Generated by Django 5.1.15 on 2026-07-28 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('rows_created', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('rows_updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('rows_failed', models.PositiveIntegerField(default=0, verbose_name='С ошибками')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('preview', 'Предпросмотр'), ('success', 'Применён'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Загрузка прайса',
                'verbose_name_plural': 'Загрузки прайса',
                'ordering': ['-created_at'],
            },
        ),
    ]
