# Generated by Django 5.1.15 on 2026-07-28 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Магазин', max_length=255, verbose_name='Название магазина')),
                ('logo', models.ImageField(blank=True, upload_to='shop/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('primary_color', models.CharField(default='#2563eb', help_text='HEX, например #2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате HEX, например #2563eb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Фирменный цвет')),
                ('telegram_username', models.CharField(blank=True, help_text='Без @, например: myshop', max_length=64, verbose_name='Telegram продавца')),
                ('whatsapp_phone', models.CharField(blank=True, help_text='Только цифры с кодом страны, например: 998901234567', max_length=20, verbose_name='WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('phone_secondary', models.CharField(blank=True, max_length=32, verbose_name='Доп. телефон')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('map_link', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('work_hours', models.CharField(blank=True, help_text='Например: Пн–Сб 9:00–18:00', max_length=255, verbose_name='Часы работы')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_channel_url', models.URLField(blank=True, verbose_name='Telegram-канал')),
                ('currency_label', models.CharField(default='сум', max_length=32, verbose_name='Валюта')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 — без ограничения', max_digits=12, verbose_name='Минимальная сумма заказа')),
                ('order_message_header', models.CharField(default='Здравствуйте! Хочу заказать:', help_text='Первая строка сообщения, которое уходит в Telegram/WhatsApp', max_length=255, verbose_name='Заголовок сообщения заказа')),
                ('show_prices', models.BooleanField(default=True, help_text='Выключите, если цены только по запросу', verbose_name='Показывать цены')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
    ]
