# Generated by Django 5.1.15 on 2026-07-30 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='theme',
            field=models.CharField(choices=[('emerald', 'Изумруд')], default='emerald', help_text='Цветовой пресет витрины (светлая/тёмная переключаются на сайте)', max_length=32, verbose_name='Тема оформления'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='primary_color',
            field=models.CharField(blank=True, help_text='HEX, например #0F7B5F. Если заполнен — перебивает акцент темы. Пусто — цвет из темы.', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате HEX, например #2563eb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Фирменный цвет'),
        ),
    ]
