# Generated by Django 5.1.15 on 2026-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0002_shopsettings_theme_alter_shopsettings_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='address_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='currency_label_ru',
            field=models.CharField(default='сум', max_length=32, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='currency_label_uz',
            field=models.CharField(default='сум', max_length=32, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='name_ru',
            field=models.CharField(default='Магазин', max_length=255, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='name_uz',
            field=models.CharField(default='Магазин', max_length=255, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='order_message_header_ru',
            field=models.CharField(default='Здравствуйте! Хочу заказать:', help_text='Первая строка сообщения, которое уходит в Telegram/WhatsApp', max_length=255, null=True, verbose_name='Заголовок сообщения заказа'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='order_message_header_uz',
            field=models.CharField(default='Здравствуйте! Хочу заказать:', help_text='Первая строка сообщения, которое уходит в Telegram/WhatsApp', max_length=255, null=True, verbose_name='Заголовок сообщения заказа'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='work_hours_ru',
            field=models.CharField(blank=True, help_text='Например: Пн–Сб 9:00–18:00', max_length=255, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='work_hours_uz',
            field=models.CharField(blank=True, help_text='Например: Пн–Сб 9:00–18:00', max_length=255, null=True, verbose_name='Часы работы'),
        ),
    ]
