# Generated by Django 5.1.15 on 2026-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0003_shopsettings_address_ru_shopsettings_address_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Крупный заголовок в шапке главной. Пусто — покажем название.', max_length=120, verbose_name='Слоган на главной'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='tagline_ru',
            field=models.CharField(blank=True, help_text='Крупный заголовок в шапке главной. Пусто — покажем название.', max_length=120, null=True, verbose_name='Слоган на главной'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='tagline_uz',
            field=models.CharField(blank=True, help_text='Крупный заголовок в шапке главной. Пусто — покажем название.', max_length=120, null=True, verbose_name='Слоган на главной'),
        ),
    ]
