# Generated by Django 5.1.15 on 2026-08-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0004_shopsettings_tagline_shopsettings_tagline_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='order_message_footer',
            field=models.CharField(blank=True, default='', help_text='Необязательная последняя строка. Например: «Укажите адрес доставки»', max_length=255, verbose_name='Подпись сообщения заказа'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='order_message_footer_ru',
            field=models.CharField(blank=True, default='', help_text='Необязательная последняя строка. Например: «Укажите адрес доставки»', max_length=255, null=True, verbose_name='Подпись сообщения заказа'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='order_message_footer_uz',
            field=models.CharField(blank=True, default='', help_text='Необязательная последняя строка. Например: «Укажите адрес доставки»', max_length=255, null=True, verbose_name='Подпись сообщения заказа'),
        ),
    ]
