# Generated by Django 5.1.15 on 2026-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0005_shopsettings_order_message_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='banners_enabled',
            field=models.BooleanField(default=False, help_text='Hero-слайдер вверху главной. По умолчанию выключен.', verbose_name='Показывать баннеры на главной'),
        ),
    ]
