# Generated by Django 5.1.15 on 2026-08-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0006_shopsettings_banners_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='theme',
            field=models.CharField(choices=[('emerald', 'Изумруд (зелёная, мягкая)'), ('sunset', 'Sunset (тёплая, с засечками)')], default='emerald', help_text='Цветовой пресет витрины (светлая/тёмная переключаются на сайте)', max_length=32, verbose_name='Тема оформления'),
        ),
    ]
