# Generated by Django 5.1.15 on 2026-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0007_alter_shopsettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='theme',
            field=models.CharField(choices=[('noir', 'Noir (чёрная, по умолчанию)'), ('emerald', 'Emerald (зелёная)'), ('ocean', 'Ocean (синяя)'), ('violet', 'Violet (фиолетовая)'), ('rose', 'Rose (розовая)'), ('sunset', 'Sunset (тёплая, с засечками)')], default='noir', help_text='Цветовой пресет витрины (светлая/тёмная переключаются на сайте)', max_length=32, verbose_name='Тема оформления'),
        ),
    ]
