# Generated by Django 5.1.15 on 2026-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0008_alter_shopsettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='banner_format',
            field=models.CharField(choices=[('wide', 'Широкий (3:1)'), ('classic', 'Классический (12:5)'), ('mobile', 'Высокий (16:9)')], default='wide', help_text='Один размер для всех слайдов — карусель не прыгает по высоте.', max_length=16, verbose_name='Формат баннеров'),
        ),
    ]
