# Generated by Django 5.1.15 on 2026-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0010_alter_shopsettings_banner_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='banner_format',
            field=models.CharField(choices=[('wide', 'Широкий (3:1)'), ('classic', 'Классический (12:5)'), ('mobile', 'Высокий (16:9)')], default='wide', help_text='Единый размер всех баннеров. Делайте картинки под эту пропорцию — без обрезки.', max_length=16, verbose_name='Формат баннеров'),
        ),
    ]
