# Generated by Django 5.1.15 on 2026-08-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0011_alter_shopsettings_banner_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='about_enabled',
            field=models.BooleanField(default=False, verbose_name='Показывать блок «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='shop/', verbose_name='Фото для «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='about_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='about_text_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='about_text_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Заголовок «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='about_title_ru',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Заголовок «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='about_title_uz',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Заголовок «О нас»'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='telegram_float_enabled',
            field=models.BooleanField(default=False, help_text='Круглая кнопка в углу экрана — быстрый заказ. Нужен заполненный Telegram продавца.', verbose_name='Плавающая кнопка Telegram'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust1_icon',
            field=models.CharField(blank=True, choices=[('tag', 'Ценник (опт/розница)'), ('truck', 'Грузовик (доставка)'), ('users', 'Клиенты'), ('calendar', 'Календарь (с какого года)'), ('box', 'Коробка (наличие на складе)'), ('shield', 'Щит (гарантия/качество)'), ('clock', 'Часы работы'), ('percent', 'Скидки'), ('star', 'Звезда (качество)'), ('wallet', 'Кошелёк (цены)')], default='tag', max_length=16, verbose_name='Плашка 1 · иконка'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust1_text',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Плашка 1 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust1_text_ru',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 1 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust1_text_uz',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 1 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust2_icon',
            field=models.CharField(blank=True, choices=[('tag', 'Ценник (опт/розница)'), ('truck', 'Грузовик (доставка)'), ('users', 'Клиенты'), ('calendar', 'Календарь (с какого года)'), ('box', 'Коробка (наличие на складе)'), ('shield', 'Щит (гарантия/качество)'), ('clock', 'Часы работы'), ('percent', 'Скидки'), ('star', 'Звезда (качество)'), ('wallet', 'Кошелёк (цены)')], default='truck', max_length=16, verbose_name='Плашка 2 · иконка'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust2_text',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Плашка 2 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust2_text_ru',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 2 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust2_text_uz',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 2 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust3_icon',
            field=models.CharField(blank=True, choices=[('tag', 'Ценник (опт/розница)'), ('truck', 'Грузовик (доставка)'), ('users', 'Клиенты'), ('calendar', 'Календарь (с какого года)'), ('box', 'Коробка (наличие на складе)'), ('shield', 'Щит (гарантия/качество)'), ('clock', 'Часы работы'), ('percent', 'Скидки'), ('star', 'Звезда (качество)'), ('wallet', 'Кошелёк (цены)')], default='users', max_length=16, verbose_name='Плашка 3 · иконка'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust3_text',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Плашка 3 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust3_text_ru',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 3 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust3_text_uz',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 3 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust4_icon',
            field=models.CharField(blank=True, choices=[('tag', 'Ценник (опт/розница)'), ('truck', 'Грузовик (доставка)'), ('users', 'Клиенты'), ('calendar', 'Календарь (с какого года)'), ('box', 'Коробка (наличие на складе)'), ('shield', 'Щит (гарантия/качество)'), ('clock', 'Часы работы'), ('percent', 'Скидки'), ('star', 'Звезда (качество)'), ('wallet', 'Кошелёк (цены)')], default='box', max_length=16, verbose_name='Плашка 4 · иконка'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust4_text',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Плашка 4 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust4_text_ru',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 4 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust4_text_uz',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Плашка 4 · текст'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trust_enabled',
            field=models.BooleanField(default=False, verbose_name='Показывать плашки доверия'),
        ),
    ]
