# Generated by Django 5.1.15 on 2026-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0012_shopsettings_about_enabled_shopsettings_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='delivery_note',
            field=models.CharField(blank=True, default='', help_text='Например: Доставка по городу от 1 дня', max_length=120, verbose_name='Доставка (текст в полосе)'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='delivery_note_ru',
            field=models.CharField(blank=True, default='', help_text='Например: Доставка по городу от 1 дня', max_length=120, null=True, verbose_name='Доставка (текст в полосе)'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='delivery_note_uz',
            field=models.CharField(blank=True, default='', help_text='Например: Доставка по городу от 1 дня', max_length=120, null=True, verbose_name='Доставка (текст в полосе)'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='topbar_enabled',
            field=models.BooleanField(default=False, help_text='Тонкая полоса над шапкой: город, доставка, часы, телефон.', verbose_name='Показывать инфо-полосу сверху'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='topbar_location',
            field=models.CharField(blank=True, default='', help_text='Например: Ташкент. Кликается на карту, если задана ссылка на карту.', max_length=80, verbose_name='Город/локация в полосе'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='topbar_location_ru',
            field=models.CharField(blank=True, default='', help_text='Например: Ташкент. Кликается на карту, если задана ссылка на карту.', max_length=80, null=True, verbose_name='Город/локация в полосе'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='topbar_location_uz',
            field=models.CharField(blank=True, default='', help_text='Например: Ташкент. Кликается на карту, если задана ссылка на карту.', max_length=80, null=True, verbose_name='Город/локация в полосе'),
        ),
    ]
