# Generated by Django 5.1.15 on 2026-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0013_shopsettings_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='faq1_a',
            field=models.TextField(blank=True, default='', verbose_name='Ответ 1'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq1_a_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 1'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq1_a_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 1'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq1_q',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Вопрос 1'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq1_q_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 1'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq1_q_uz',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 1'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq2_a',
            field=models.TextField(blank=True, default='', verbose_name='Ответ 2'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq2_a_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 2'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq2_a_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 2'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq2_q',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Вопрос 2'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq2_q_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 2'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq2_q_uz',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 2'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq3_a',
            field=models.TextField(blank=True, default='', verbose_name='Ответ 3'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq3_a_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 3'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq3_a_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 3'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq3_q',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq3_q_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq3_q_uz',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq4_a',
            field=models.TextField(blank=True, default='', verbose_name='Ответ 4'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq4_a_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 4'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq4_a_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 4'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq4_q',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Вопрос 4'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq4_q_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 4'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq4_q_uz',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 4'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq5_a',
            field=models.TextField(blank=True, default='', verbose_name='Ответ 5'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq5_a_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 5'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq5_a_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ответ 5'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq5_q',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Вопрос 5'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq5_q_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 5'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq5_q_uz',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Вопрос 5'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='faq_enabled',
            field=models.BooleanField(default=False, verbose_name='Показывать FAQ'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='howto_enabled',
            field=models.BooleanField(default=False, verbose_name='Показывать блок «Как заказать»'),
        ),
    ]
