# Generated by Django 5.1.15 on 2026-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0014_shopsettings_faq1_a_shopsettings_faq1_a_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='banner_format',
            field=models.CharField(choices=[('strip', 'Полоса (4:1) — самый низкий'), ('wide', 'Широкий (3:1)'), ('classic', 'Классический (12:5)'), ('half', 'Средний (2:1)'), ('mobile', 'Высокий (16:9)')], default='wide', help_text='Единый размер всех баннеров. Делайте картинки под эту пропорцию — без обрезки. Чем шире формат, тем ниже баннер.', max_length=16, verbose_name='Формат баннеров'),
        ),
    ]
