# Generated by Django 5.1.15 on 2026-08-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0015_alter_shopsettings_banner_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='banner_format',
        ),
    ]
