# Generated by Django 5.1.15 on 2026-08-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0016_remove_shopsettings_banner_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust1_icon',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust1_text',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust1_text_ru',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust1_text_uz',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust2_icon',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust2_text',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust2_text_ru',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust2_text_uz',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust3_icon',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust3_text',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust3_text_ru',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust3_text_uz',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust4_icon',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust4_text',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust4_text_ru',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust4_text_uz',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='trust_enabled',
        ),
    ]
