# Generated by Django 5.1.15 on 2026-07-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Код заказа')),
                ('payload', models.JSONField(verbose_name='Состав заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Заказ по ссылке',
                'verbose_name_plural': 'Заказы по ссылке',
                'ordering': ['-created_at'],
            },
        ),
    ]
