# Generated by Django 5.1.15 on 2026-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_blob',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
