# Generated by Django 5.1.15 on 2026-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Ключ для импорта прайса. Оставьте пустым — сгенерируется автоматически.', max_length=64, unique=True, verbose_name='Артикул'),
        ),
    ]
