# Generated by Django 5.1.15 on 2026-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=60, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=60, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=120, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Подзаголовок')),
                ('subtitle_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='Подзаголовок')),
                ('badge', models.CharField(blank=True, max_length=30, verbose_name='Текст плашки')),
                ('badge_ru', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текст плашки')),
                ('badge_uz', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текст плашки')),
                ('button_text', models.CharField(blank=True, max_length=30, verbose_name='Текст кнопки')),
                ('button_text_ru', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текст кнопки')),
                ('button_text_uz', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, help_text='URL или путь, напр. /catalog/ или https://…', max_length=500, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Фон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Показ с')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='Показ по')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', 'id'],
            },
        ),
    ]
