# Generated by Django 5.1.15 on 2026-08-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('упак', 'упак'), ('набор', 'набор'), ('пара', 'пара'), ('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл'), ('м', 'м'), ('рулон', 'рулон')], default='шт', max_length=8, verbose_name='Единица'),
        ),
    ]
