# Generated by Django 5.1.15 on 2026-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Заголовок'),
        ),
    ]
